version: "3"

silent: true

vars:
  YEARS: 6

tasks:
  setup:
    cmds:
      - ./setup.sh

  venv:
    cmds:
      - python3 -m venv .venv

  install:
    cmds:
      - source .venv/bin/activate && python3 -m pip install --upgrade pip --progress-bar off > /dev/null
      - source .venv/bin/activate && python3 -m pip install -r requirements.txt --progress-bar off > /dev/null

  upgrade:
    cmds:
      - source .venv/bin/activate && python3 -m pip install -U datalex-cli --progress-bar off
      - cd dql && npm install @duckcodeailabs/dql-cli@latest --no-save --no-audit --no-fund

  deps:
    cmds:
      - source .venv/bin/activate && dbt deps --profiles-dir .

  gen:
    cmds:
      - source .venv/bin/activate && jafgen {{.YEARS}} && rm -rf seeds/jaffle-data && mv jaffle-data seeds

  seed:
    cmds:
      - >
        source .venv/bin/activate && dbt seed --full-refresh --profiles-dir . --vars '{"load_source_data": true}'

  build:
    cmds:
      - source .venv/bin/activate && dbt seed --full-refresh --profiles-dir .
      - source .venv/bin/activate && dbt build --profiles-dir . --exclude resource_type:seed

  docs:
    cmds:
      - source .venv/bin/activate && dbt docs generate --profiles-dir .

  clean:
    cmds:
      - rm -rf jaffle-data target dbt_packages logs jaffle_shop.duckdb jaffle_shop.duckdb.wal

  load:
    cmds:
      - task: venv
      - task: install
      - task: deps
      - task: gen
      - task: build

  run:
    cmds:
      - task: deps
      - task: build

  verify:
    cmds:
      - task: deps
      - task: build
      - task: docs
